[tox]

min_version = 4.11.0

envlist =
    py{311,312}-lint,
    py{311,312}-Plone{60,61},
    coverage-report,

skip_missing_interpreters = True


[gh-actions]
python =
    3.11: py311
    3.12: py312


[gh-actions:env]
PLONE-VERSION =
    Plone60: Plone60
    Plone61: Plone61


[testenv]
skip_install = true

extras =
    develop
    test

commands =
    {envbindir}/buildout -c {toxinidir}/{env:version_file} buildout:directory={envdir} buildout:develop={toxinidir} bootstrap
    {envbindir}/buildout -c {toxinidir}/{env:version_file} buildout:directory={envdir} buildout:develop={toxinidir} install test
    coverage run {envbindir}/test --auto-color {posargs}

setenv =
    COVERAGE_FILE=.coverage.{envname}
    Plone60: version_file=test_plone60.cfg
    Plone61: version_file=test_plone61.cfg

deps =
    Plone60: -rrequirements_plone60.txt
    Plone61: -rrequirements_plone61.txt
    coverage

allowlist_externals =
    mkdir

[testenv:coverage-report]
skip_install = true
usedevelop = True
basepython = python3.12

deps =
    coverage
    -cconstraints_plone60.txt

setenv =
    COVERAGE_FILE=.coverage

commands =
    coverage erase
    coverage combine
    coverage html
    coverage xml
    coverage report


[lint]
skip_install = true

deps =
    isort
    flake8
    flake8-html
    flake8-coding
    flake8-debugger
    flake8-deprecated
    flake8-print
    mccabe

commands =
    mkdir -p {toxinidir}/reports/flake8
    - flake8 --format=html --htmldir={toxinidir}/reports/flake8 --doctests src setup.py
    flake8 --doctests src setup.py
    isort --check-only {toxinidir}/src/Products

allowlist_externals =
    mkdir

[testenv:isort-apply]
skip_install = true

deps =
    isort

commands =
    isort setup.py {toxinidir}/src

[testenv:black-check]
basepython = python3.12
skip_install = True
deps =
    -cconstraints.txt
    black

commands =
    black --check --diff -v src setup.py


[testenv:black-enforce]
basepython = python3.12
skip_install = True
deps =
    -cconstraints.txt
    black

commands =
    black -v src setup.py

[testenv:py311-lint]
basepython = python3.11
skip_install = true
deps = {[lint]deps}
commands = {[lint]commands}
allowlist_externals = {[lint]allowlist_externals}

[testenv:py312-lint]
basepython = python3.12
skip_install = true
deps = {[lint]deps}
commands = {[lint]commands}
allowlist_externals = {[lint]allowlist_externals}

[testenv:update_translation]
skip_install = true

deps =
    i18ndude

commands =
    i18ndude find-untranslated
    i18ndude rebuild-pot
    i18ndude merge
    i18ndude sync
    i18ndude list

[testenv:release]
skip_install = true

deps =
    zest.releaser[recommended]

commands =
    fullrelease --no-input -v
